name: CI

on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Terraform format check
        run: make terraform-fmt-check